apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: search
  name: search
spec:
  type: NodePort
  ports:
  - name: http 
    port: 8082
    nodePort: 31111
  selector:
    io.kompose.service: search
