apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-geo
  name: mongodb-geo
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30001
  selector:
    io.kompose.service: mongodb-geo
