apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30005
  selector:
    io.kompose.service: mongodb-reservation
