apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  template:
    metadata:
      labels:
        io.kompose.service: jaeger
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node1
      containers:
      - image: jaegertracing/all-in-one:latest
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 14269
        - containerPort: 5778
          hostPort: 5778
        - containerPort: 14268
          hostPort: 14268
        - containerPort: 14267
        - containerPort: 16686
          hostPort: 16686
        - containerPort: 5775
          hostPort: 5775
          protocol: UDP
        - containerPort: 6831
          hostPort: 6831
          protocol: UDP
        - containerPort: 6832
          hostPort: 6832
          protocol: UDP
      restartPolicy: Always
