apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rate
  name: rate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: rate
  template:
    metadata:
      labels:
        io.kompose.service: rate
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000321000
      initContainers:
      - name: configwriter
        securityContext:    
          runAsNonRoot: true
        env:
        - name: LOGICNODEIP
          value: 172.16.84.130
        - name: DATANODEIP
          value: 172.16.84.128
        image: youngpig/configwriter:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: varconfig
          mountPath: /var/configFiles
      containers:
      - command:
        - rate
        image: youngpig/hotel_reservation
        imagePullPolicy: IfNotPresent
        name: hotelreservation-rate
        ports:
        - containerPort: 8084
          hostPort: 8084
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /go/src/github.com/harlow/go-micro-services/config
          name: varconfig
      restartPolicy: Always
      volumes:
      - name: varconfig
        emptyDir: {}
