apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: reservation
  name: reservation
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: reservation
  template:
    metadata:
      labels:
        io.kompose.service: reservation
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node1
      containers:
      - command:
        - reservation
        image: yz2297/hotel_reservation
        imagePullPolicy: IfNotPresent
        name: hotelreservation-reservation
        ports:
        - containerPort: 8087
          hostPort: 8087
        volumeMounts:
        - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
          name: reservation-claim0
      restartPolicy: Always
      volumes:
      - name: reservation-claim0
        hostPath:
          path: /root/Go-operator-projects/hotelReservation-operator/original/hotelRes/config.json
          type: FileOrCreate

