apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: user
  template:
    metadata:
      labels:
        io.kompose.service: user
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node1
      containers:
      - command:
        - user
        image: yz2297/hotel_reservation
        imagePullPolicy: IfNotPresent
        name: hotelreservation-user
        ports:
        - containerPort: 8086
          hostPort: 8086
        volumeMounts:
        - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
          name: user-claim0
      restartPolicy: Always
      volumes:
      - name: user-claim0
        hostPath:
          path: /root/Go-operator-projects/hotelReservation-operator/original/hotelRes/config.json
          type: FileOrCreate
