apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-rate
  name: mongodb-rate
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30003
  selector:
    io.kompose.service: mongodb-rate
