apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: memcached-rate
  name: memcached-rate
spec:
  type: NodePort
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
    nodePort: 31001
  selector:
    io.kompose.service: memcached-rate
