apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-profile
  name: mongodb-profile
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30002
  selector:
    io.kompose.service: mongodb-profile
