apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: memcached-reserve
  name: memcached-reserve
spec:
  type: NodePort
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
    nodePort: 31003
  selector:
    io.kompose.service: memcached-reserve
