apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-recommendation
  name: mongodb-recommendation
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30004
  selector:
    io.kompose.service: mongodb-recommendation
