apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
      labels:
        io.kompose.service: consul
    spec:
      nodeSelector:
        kubernetes.io/hostname: work-node1
      containers:
      - image: consul:latest
        imagePullPolicy: IfNotPresent
        name: consul
        ports:
        - containerPort: 8300
          hostPort: 8300
        - containerPort: 8400
          hostPort: 8400
        - containerPort: 8500
          hostPort: 8500
        - containerPort: 53
          hostPort: 8600
          protocol: UDP
      restartPolicy: Always
