apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: mongodb-geo
  name: mongodb-geo
spec:
  serviceName: "mongodb-geo"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-geo
  volumeClaimTemplates:
  - metadata:
      name: geo 
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi 
  template:
    metadata:
     labels:
       io.kompose.service: mongodb-geo
    spec:
     nodeSelector:
        kubernetes.io/hostname: data-node
     serviceAccount: nfs-provisioner
     containers:
      - image: mongo
        imagePullPolicy: IfNotPresent
        name: hotelreservation-mongodb-geo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: geo
