apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-user
  name: mongodb-user
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30006
  selector:
    io.kompose.service: mongodb-user
